version: v1

labels:
  - label: "enhancement"
    sync: true
    matcher:
      title: "^feat: .*"
      commits: "^feat: .*"

  - label: "bug"
    sync: true
    matcher:
      title: "^fix: .*"
      commits: "^fix: .*"

  - label: "dependencies"
    sync: true
    matcher:
      title: "^build\x28deps\x29: .*"
      commits: "^build\x28deps\x29: .*"

  - label: "test"
    sync: true
    matcher:
      title: "^test: .*"
      commits: "^test: .*"

checks:
  - context: "Semantic Pull Request"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - enhancement
        - bug
        - dependences
        - test
