name: Azure Static Web Apps CI/CD Production

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup dependencies
        run: npm i
      - name: Build
        run: VITE_VERSION=$GITHUB_SHA npm run build:production
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_PEBBLE_05A83D103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist" # App source code path
          output_location: "/dist"
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
        env:
          NODE_VERSION: 15.3.0
        env:
          API_URL: https://store.gliff.ai
          NODE_VERSION: 15.3.0
